### ISSUE TITLE
Ctrl-e as the hot key?

### ISSUE THREAD

**Issue by jflorian** [smblott-github/text-aid-too#13]
Back when I was on firefox and using a similar plugin (textern IIRC), I had my trigger set to Ctrl-e.  My muscle memory is deep as result.  Is there any way to use that with text-aid-too?  Chromium seems to steal the key.

**Comment by smblott-github** [comment]
You can change the key on the options page.  Unfortunately, if Chromium is stealing the key (which it does with some keys), there's nothing to be done.  For those keys, Chromium *never* passes them to the extension.

**Comment by jflorian** [comment]
Okay, that's what I figured (about the key stealing), but it's good to have confirmed.  I even tried entering the integer value directly, but no dice.

Regardless, thanks for the feedback and the extension.  I use it many times a day now.
