### ISSUE TITLE
Give focus back to Chrome after editing

### ISSUE THREAD

**Issue by adrienverge** [smblott-github/text-aid-too#3]
First, thanks for this very cool piece of software!

Currently after editing (when quitting Vim for intance), focus is not restored to the Chromium window, which means the user has to use the mouse or a key combination to go back to the browser. It's a bit annoying.

Is it possible to give focus back?

**Comment by smblott-github** [comment]
Hmm.  For me, the focus does go back to the browser.

Let me think about this.
