### ISSUE TITLE
prolem with gvim and dbus - solved

### ISSUE THREAD

**Issue by p-phillips** [smblott-github/text-aid-too#5]
Hi

When running under Ubuntu 16.04 with gnome-shell, gvim would come up OK but I had an error message similar to this: http://vi.stackexchange.com/questions/6222/how-to-resolve-gvim-startup-error-no-d-bus-daemon-running

The solution was to use this:

`Environment="TEXT_AID_TOO_EDITOR=dbus-launch gvim -f"`

Perhaps you can add to the README

Pete

**Comment by smblott-github** [comment]
Done (7ffe9f60aee7118a6c2d7a63ae46457a43e7e2b3).
