### ISSUE TITLE
Using vim instead of gvim

### ISSUE THREAD

**Issue by shaoran** [smblott-github/text-aid-too#6]
I installed `text-aid-too` and it worked without a problem. However if I run `text-aid-too` with the `--editor vim` option, I got this:

```
ping: ok
edit: /tmp/shaoran-text-aid-too-41432-300617827.txt
exec: vim /tmp/shaoran-text-aid-too-41432-300617827.txt
ping: ok
```

`vim` is definitely running, I can see the process with `ps`, but I don't see it on the same console that `text-aid-too` is running. So I thought that the `ping: ok` lines could be the problem so I removed the `console.log` line that prints the `ping: ok` message. That didn't help either.

The next thing I tried was to write a wrapper around vim that spawns a new terminal

```
#!/bin/bash

set -e

exec gnome-terminal --hide-menubar -e "vim $@"`
```

Using `--editor ~/openvim` a new terminal with vim gets started, but `text-aid-too` already thinks that the process is dead and sent back the same content to chrome:

```
ping: ok
edit: /tmp/shaoran-text-aid-too-41774-867272123.txt
exec: /home/shaoran/openvim /tmp/shaoran-text-aid-too-41774-867272123.txt
  send: /tmp/shaoran-text-aid-too-41774-867272123.txt [827]
  done: /tmp/shaoran-text-aid-too-41774-867272123.txt
ping: ok
```

At the time the terminal is open and vim executed, the `send` and `done` messages are already on the console. The tmp file is also gone. What could I do to use vim on the same terminal or to spawn a terminal running vim? Could it be an issue with `watchr`?

**Comment by smblott-github** [comment]
I think `gnome-terminal` is just a bad choice of terminal.  It insists on forking, and there doesn't seem to be a way to stop that behaviour.

These should work...

    xterm -e vim
    urxvt -e vim

**Comment by shaoran** [comment]
I like the `gnome-terminal` in version 2.32.x. I've been using it for many years now and I like it. Changing it to `xterm` or `urxvt` is not an alternative for me.

Anyway, I ended up reconfiguring my gvim so that it looks and feels more like my vim. That's good enough for me right now. Thanks anyway.
